variable "vpc_cidr_block" {}
variable "private_subnet_cidr_blocks" {}
variable "public_subnet_cidr_blocks" {}
variable "env_prefix" {}
variable "region" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "resource_created_by" {}
variable "vpc_name" {}
variable "role_name" {}
variable "eks_node_group" {}
variable "eks_node_instance_type" {}